name: sakin_app
description: A pure offline Prayer & Habit tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  provider: ^6.1.1

  # Data & Engine
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adhan: ^2.0.0
  
  # Background & Notifications
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1 # للمساعدة في الأذونات
  just_audio: ^0.9.36 # لتشغيل الأذان
  geolocator: ^13.0.1 # لتحديد موقع المستخدم
  geocoding: ^3.0.0 # لجلب اسم المدينة من الإحداثيات

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
